### PR TITLE
fix(doc): Removed duplicated doc code in doc/xcodehc.txt

### PR DESCRIPTION
**Pull request by vismaybhargav**
I noticed an error when trying to install the plugin on my Neovim. I found out it was an error with duplicate documentation in the doc/xcodehc.txt file. This pull request fixes that by removing it.

### CODE REVIEW

**Comment by bronzehedwick** [comment]
Thanks @VizB!

This theme is generated via Colortemplate. Can you make the necessary changes to the [template](https://github.com/lunacookies/vim-colors-xcode/tree/master/templates) files, run the script, and commit all in your PR?

**Comment by VizB** [comment]
Sure! I'll get on that.

**Comment by Faetu** [comment]
@vismaybhargav 
How can I install your version?

**Comment by vismaybhargav** [comment]
> @vismaybhargav How can I install your version?

You can download it by going to my profile and go to the repo with the same name. then when you put that into your package manager just do vismaybhargav/vim-colors-xcode

**Comment by hernancerm** [comment]
I'm seeing this same issue on installation in Neovim. I'm using [Lazy](https://github.com/folke/lazy.nvim) as the plugin manager.
```
...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:95: Vim:E154: Duplicate tag "g:xcodehc_dim_punctuation" in file /Users/hernancervera/.local/share/nvim/lazy/vim-colors-xcode/doc/xcodehc.txt
``` 
image
Installing vismaybhargav's version was successful (`vismaybhargav/vim-colors-xcode`).

**Comment by bronzehedwick** [comment]
Looks like I at mentioned the wrong person to get this issue fixed. @vismaybhargav can you update your PR to use color template?

> This theme is generated via Colortemplate. Can you make the necessary changes to the [template](https://github.com/lunacookies/vim-colors-xcode/tree/master/templates) files, run the script, and commit all in your PR?

**Comment by Perkelo** [comment]
I made an [AUR Package](https://aur.archlinux.org/packages/vim-colors-xcode-git) for this repo. However, since this PR hasn't been merged yet I had to use a fork with the config file deduplicated. Once the commit is merged, I will refer the package to the original repo

**Comment by Perkelo** [comment]
Thanks, updated

**Pull request merged**
